import { Inter } from "next/font/google";
import "./globals.css";
import Headers from "./ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Pixabay copy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <Headers />
        {children}
      </body>
    </html>
  );
}
